### ISSUE TITLE
The plugin_name property is not used when the plugin is a class/function.

### ISSUE THREAD

**Issue by hparkertt** [koopjs/koop-core#90]
The logic at [src/index.js:334](https://github.com/koopjs/koop-core/blob/040712cdfc99f6299698b095273baf8a0a6f4335/src/index.js#L334) seems to be backwards.  When creating a plugin as a class or function, the `name` property is a read-only property from the `Function` object.  In this scenario, we will never get to the `plugin_name` property.  This causes an issue when uglifying code, because the value of `Plugin.name` becomes the new unrecognizable name given to the function in the uglification process.  If the logic was instead: `Plugin.plugin_name || Plugin.name`, the `name` property would serve as a fail-safe and the `plugin_name` property would act as an override.

If this is not the intended use of `plugin_name`, then a different solution needs to be explored to resolve the bug introduced by uglifying logic.

**Comment by rgwozdz** [comment]
`plugin_name` is a deprecated property from Koop 2.x; And I think you are correct that the logic is backwards. The use of `Plugin.name` is intentional, we just want to use the name of function defined by the plugin. Sorry that is causing you problems - but why you are uglifying server code?

You're welcome to PR.  Change the logic and introduce a new property called `pluginName` - we want to use camelCase moving forward.

**Comment by hparkertt** [comment]
Okay, that makes sense.  It's definitely a no-brainer to use the function name in most cases.  I'm uglifying my code as part of a bundling process.  My end goal is to reduce the size of our production package as much as possible.  Unfortunately express (and koop, I think?) utilize 'dynamic' requires, thus they aren't easily bundle-able, but that's a different topic.

I'll add that property in camelCase and put together a PR.

Thanks for the quick reply!
